# Basic data types

In [13]:
#Integers 
x = 3
#print the type of x
print(type(x))

# Addition : add 1 to x and print the result
print(x+1)
# Subtraction; subtract 1 from x and print the result
print(x-1)
# Multiplication; multiply x with 2 and print the result
print(x*2)
# Exponentiation; print the square of x
print(x**2)

<class 'int'>
4
2
6
9


In [14]:
#floats
y = 2.5
#print the type of y
print(type(y))
#use operator *= to double the value of y and print y 
y*=2
print(y)
#use operator += to add 3 to y and print y 
y+=3
print(y)


<class 'float'>
5.0
8.0


In [15]:
#Strings 
s = "hello"
# Capitalize the above string and print it
print(s.capitalize())
#Convert the string to uppercase and print it
print(s.upper())
# Right-justify the string, padding with 2 spaces print it;
#doubt to do
print(s.rjust(7))
# Center the string, padding with 2 spaces print it;
print(s.center(7))
# Replace all instances of letter l  with "(ell)" and print it;
print(s.replace('l','ell'))
str = " world "
# Strip leading and trailing whitespace in the above string and print
print(str.strip())

Hello
HELLO
  hello
 hello 
heellello
world


# Containers

In [16]:
#Lists
#create a list of first five natural numbers
list1 = [1,2,3,4]
#change the 3rd element to "foo" and print list1
list1[2]="foo"
print(list1)
list2 = ["bar"]
#append list2 to list1 and print the result
list1.append(list2)
print(list1)
#add list2 to list1 using extend and print the result
list1.extend(list2)
print(list1)
#remove last element in list1 using pop and print list1
list1.pop()
print(list1)



[1, 2, 'foo', 4]
[1, 2, 'foo', 4, ['bar']]
[1, 2, 'foo', 4, ['bar'], 'bar']
[1, 2, 'foo', 4, ['bar']]


In [17]:
#Slicing 
nums = list(range(5))
#print a slice from index 2 to 4 (exclusive)
print(nums[2:4])
#print a slice from index 2 to 4 (exclusive)
print(nums[2:4])
# Slice indices can be negative; 
print(nums[:-3]) 
# Assign the [8,9] new list to a slice from index 2 to 4 (exclusive)
nums[2:4] = [8, 9]
print(nums)

[2, 3]
[2, 3]
[0, 1]
[0, 1, 8, 9, 4]


In [18]:
#Loops
nums = [0, 1, 2, 3, 4]
squares = []
# append squares of each element in nums to squares using for loop
squares=[i**2 for i in nums]
print(squares)
####

animals = ['cat', 'dog', 'monkey']
#print index and elements in the list using enumerate and for loop
print([i for i in enumerate(animals)])

#print squares of even numbers using list comprehensions
nums = [0, 1, 2, 3, 4]
even_squares = [i**2 for i in nums if i%2==0 ]
print(even_squares)

[0, 1, 4, 9, 16]
[(0, 'cat'), (1, 'dog'), (2, 'monkey')]
[0, 4, 16]


In [19]:
#Dictionaries
#create a dictionary with keys = (cat, dog) and items = (cute,furry)
d = {"cat":"cute","dog":"furry"}
print(d)
#set an entry {fish:wet}
d.update({"fish":"wet"})
print(d)
#remove the entry with key= cat 
d.pop("cat")
print(d)
# Get an element with a default;
print(d.get('monkey', 'N/A'))
# get an element with key= fish and print it
print(d.get('fish'))
#print all keys in dictionary
print([i for i in d.keys()])
#print all items in dictionary
print([i for i in d.values()])

{'cat': 'cute', 'dog': 'furry'}
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
{'dog': 'furry', 'fish': 'wet'}
N/A
wet
['dog', 'fish']
['furry', 'wet']


In [20]:
#sets 
#create a set with elements cat, dog and fish
s = {"cat","dog","fish"}
print (s)
#add monkey to the set
s.add("monkey")
print(s)
#remove fish from the set 
s.remove("fish")
print(s)
#checks if an element is in the set
print('fish' in animals)

{'fish', 'dog', 'cat'}
{'fish', 'dog', 'monkey', 'cat'}
{'dog', 'monkey', 'cat'}
False


# Numpy

In [21]:
#importing the numpy package 
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
#print the shape of the array
print(b.shape)
#print an array of all zeros of shape(2,2)
array1=np.zeros((2,2))
print(array1)
#print an array of all ones of shape(1,2)
array2=np.ones((1,2))
print(array2)
#print an array of shape (3,3) with all elements in array = 7
array3=np.full((3,3),7)
print(array3)
#print an array filled with random values of shape (2,2)
array4=np.random.random((2,2))
print(array4)


(2, 3)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.74467666 0.03278025]
 [0.37285989 0.20630538]]


In [22]:
#ARRAY INDEXING

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to print out the subarray consisting of the first 2 rows and columns 1 and 2;
print(a[:2,:2])
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
z=[]
# print one element from each row of a using the indices in b
for i, v in enumerate(b):
  z.append(a[i][b[i]])
print(z)
# add 10 to one element from each row of a using the indices in b
for i, v in enumerate(b):
  a[i][b[i]] += 10

print(a)

[[1 2]
 [5 6]]
[1, 6, 7, 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [23]:
#Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])
#Print a numpy array of Booleans where elements of a are bigger than 2 ,shape=(3,2)
array1 = a>2
print(array1)
#a rank 1 array consisting of the elements of a that are bigger than 2
array2=array1.flatten()
array3=a.flatten()
c=0
array5=[]
for i in array2:
  if i==True:
    array5.append(array3[c])
  c+=1
print(array5)

x = np.array([1, 2]) 
#print data type of the array
print(x.dtype)
#create an array [[1,2],[3,4]] with data type int64.
array6=np.array([[1,2],[3,4]],dtype='int64')
print(array6.dtype)

[[False False]
 [ True  True]
 [ True  True]]
[3, 4, 5, 6]
int64
int64


In [24]:
#Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
#print elementwise addition using numpy function
print(np.add(x,y))
#print elementwise difference using numpy function
print(np.subtract(x,y))
#print elementwise multiplication using numpy function
print(np.multiply(x,y))
#print elementwise division using numpy function
print(np.divide(x,y))
#print elementwise square root using numpy function
print(np.sqrt(x))
print(np.sqrt(y))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [25]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

#print Inner product of vectors
print(np.inner(v,w))
#print matrix / vector product of x and v 
print(np.dot(x,v))
#print matrix / vector product of x and y 
print(np.dot(x,y))

219
[29 67]
[[19 22]
 [43 50]]


In [26]:
x = np.array([[1,2],[3,4]])
#print sum of all elements in array
print(np.sum(x))
#print sum of elements in each row
print(np.sum(x,axis=1))
#print sum of elements in each column
print(np.sum(x,axis=0))

10
[3 7]
[4 6]


In [12]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#Create an empty matrix with the same shape as x and print
s1=x.shape
y=np.empty(s1)
#array2=np.empty_like(x)
#print(array2)
print(y)
# create an array y by adding  the vector v to each row of the matrix x with an explicit loop 
#print y
for i in range(4):
  y[i, :] = x[i, :] + v
print(y)


#Add v to each row of x using broadcasting
#store the result in matrix y and print y
y = x + v
print(y)


[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [27]:
v = np.array([1,2,3])  
w = np.array([4,5])
#reshape v to(3,1) using numpy function and print it
print(v.reshape(3,1))


[[1]
 [2]
 [3]]
